load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:py_library.bzl", "py_library")

py_library(
    name = "bench_wide",
    srcs = ["__init__.py", "wide.py"],
    deps = [
        requirement("click"),
        requirement("flask"),
        requirement("httpx"),
        requirement("numpy"),
        requirement("pandas"),
        requirement("pydantic"),
        requirement("requests"),
    ],
    visibility = ["//visibility:public"],
)
